### PR TITLE
api helm charts

### PR DESCRIPTION
**Pull request by mohamedOuladi**
- wic api helm charts

### CODE REVIEW

**Comment by mohamedOuladi** [comment]
- Minimized both wic cli and wic api docker images (using debian as a base image and cleaning up after building steps)
- Updated restapi dependencies 
- fixed steps keys format

**Comment by mohamedOuladi** [comment]
Added docker compose file for local api dev

**Review by sclaybon — APPROVED** [review]
approved after verifying dry run with Simo

**Comment by jfennick** [comment]
I think any PR which adds code in a new language should add a linting step for it into the CI. We can merge this PR, but let's add helm linting soon.

**Pull request merged**
